on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: kushalkj/msp430-gcc-9.3.1.11:latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Formatting the code
        run: make format && git diff --quiet

      - name: Run cppcheck
        run: make cppcheck
      
      - name: Set TOOLS_PATH and run make
        run: TOOLS_PATH=/home/ubuntu/dev/tools make HW=LAUNCHPAD
