on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image:kushalkj/msp430-gcc-9.3.1.11:latest
    steps:
      -name: Checkout the repository
       uses: actions/checkout@v3
<<<<<<< HEAD
       -run: TOOLS_PATH=/home/ubuntu/dev/tools make
=======
       -run: make
>>>>>>> 01b450259674c4600239e94985d53f5290f2d9f8
       -run: make cppcheck
